var routes = {
  boneshaker: {
    name: "Bomb Voyage to Boneshaker",
    terrain: "Difficult",
    vertical: "Difficult",
    location: "cowboy",
    distance: 6.3,
    elev: 1104,
  },
  cowboyhalf: {
    name: "Cowboy Half Marathon",
    terrain: "Difficult",
    vertical: "Difficult",
    location: "cowboy",
    distance: 13,
    elev: 1700,
  },
  totheduck: {
    name: "To The Duck",
    terrain: "Difficult",
    vertical: "Difficult",
    location: "Red Rock Canyon",
    distance: 6.8,
    elev: 2500,
  },
  grandcircle: {
    name: "Grand Circle From Calico Basin",
    terrain: "Medium",
    vertical: "Medium",
    location: "Calico Basin / Red Rock",
    distance: 14,
    elev: 1849,
  },
  kfourhalf: {
    name: "Kevin's Four and a Half",
    terrain: "Medium",
    vertical: "Medium",
    location: "Moenkopi Rd",
    distance: 4.3,
    elev: 530,
  },
  charleston: {
    name: "Charleston Summit Loop",
    terrain: "Difficult",
    vertical: "Difficult",
    location: "Mt Charleston",
    distance: 18,
    elev: 6200,
  },
  moenkopi: {
    name: "Moenkopi Lollipop",
    terrain: "Easy",
    vertical: "Easy",
    location: "Calico Basin / Red Rock",
    distance: 5.7,
    elev: 690,
  },
  bearstwentytwo: {
    name: "Bear's 22",
    terrain: "Easy",
    vertical: "Easy",
    location: "Bear's Best",
    distance: 22.3,
    elev: 2377,
  },
  grateful: {
    name: "Grateful 8",
    terrain: "Medium",
    vertical: "Medium",
    location: "Cowboy Trails",
    distance: 7.9,
    elev: 1182,
  }

}
