var routes = {
  boneshaker: {
    name: "Bomb Voyage to Boneshaker",
    terrain: ["Difficult", "text-danger"],
    vertical: ["Difficult", "text-danger"],
    location: ["Cowboy Trails", "text-danger"],
    start: "<a href='https://goo.gl/maps/XNFCGV6uiGx'>Cowboy Trails parking lot</a>",
    distance: 6.3,
    elev: 1104,
  },
  cowboyhalf: {
    name: "Cowboy Half Marathon",
    terrain: ["Difficult", "text-danger"],
    vertical: ["Difficult", "text-danger"],
    location: ["Cowboy Trails", "text-danger"],
    start: "<a href='https://goo.gl/maps/XNFCGV6uiGx'>Cowboy Trails parking lot</a>",
    distance: 13,
    elev: 1700,
  },
  totheduck: {
    name: "To The Duck",
    terrain: ["Difficult", "text-danger"],
    vertical: ["Difficult", "text-danger"],
    location: ["Red Rock Canyon", "text-redrock"],
    start: "<a href='https://goo.gl/maps/eXuZ7WSfZP82'>Calico Basin Trail parking</a>",
    distance: 6.8,
    elev: 2500,
  },
  grandcircle: {
    name: "Grand Circle From Calico Basin",
    terrain: ["Medium", "text-warning"],
    vertical: ["Medium", "text-warning"],
    location: ["Calico Basin / Red Rock", "text-info"],
    start: "<a href='https://goo.gl/maps/eXuZ7WSfZP82'>Calico Basin Trail parking</a>",
    distance: 14,
    elev: 1849,
  },
  kfourhalf: {
    name: "Kevin's Four and a Half",
    terrain: ["Medium", "text-warning"],
    vertical: ["Medium", "text-warning"],
    location: ["Moenkopi Rd", "text-moenkopi"],
    start: "<a href='https://goo.gl/maps/CU8s5GZ8Z8z'>Moenkopi Rd parking lot</a>",
    distance: 4.3,
    elev: 530,
  },
  charleston: {
    name: "Charleston Summit Loop",
    terrain: ["Difficult", "text-danger"],
    vertical: ["Difficult", "text-danger"],
    location: ["Mt Charleston", "text-warning"],
    start: "<a href='https://goo.gl/maps/t4fj9pNHUuG2'>Trail Canyon Trailhead parking</a>",
    distance: 18,
    elev: 6200,
    description: "If you need some mountain training this is the place to go. Only 45 minutes outside Vegas but feels like a different world."
  },
  moenkopi: {
    name: "Moenkopi Lollipop",
    terrain: ["Easy", "text-success"],
    vertical: ["Easy", "text-success"],
    location: ["Calico Basin / Red Rock", "text-info"],
    start: "<a href='https://goo.gl/maps/eXuZ7WSfZP82'>Calico Basin Trail parking</a>",
    distance: 5.7,
    elev: 690,
  },
  bearstwentytwo: {
    name: "Bear's 22",
    terrain: ["Easy", "text-success"],
    vertical: ["Easy", "text-success"],
    location: ["Bear's Best", "text-success"],
    start: "<a href='https://goo.gl/maps/WCNyDQAUwK82'>Bear's Best Trailhead parking</a>",
    distance: 22.3,
    elev: 2377,
  },
  grateful: {
    name: "Grateful 8",
    terrain: ["Medium", "text-warning"],
    vertical: ["Medium", "text-warning"],
    location: ["Cowboy Trails", "text-danger"],
    start: "<a href='https://goo.gl/maps/XNFCGV6uiGx'>Cowboy Trails parking lot</a>",
    distance: 7.9,
    elev: 1182,
  }

}
